### ISSUE TITLE
Dungeon : eye of azshara

### ISSUE THREAD

**Issue by newonee** [newonee/Caspian#15]
npc : 97269  use restoration spell on normal mode
crushing wave spell no damage to tank
impeling spear ro tank mizane

**Comment by newonee** [comment]
npc_serpentrix_hydras   visual face bug


king deepbeard
ground slam no ignore armor

**Comment by newonee** [comment]
king deepbeard
ground slam no ignore armor

wrath of azshara
lighting strike ro nmizane
arcane bomb mesle aura mimone

**Comment by AlirezaAbsolution** [comment]
INSTANCE SPELLS

Tempest(199948):
addhaye kenar boss akhar 4ta hastan vaghti az 50yardishon rad mishi in spello bayad per 0.25 sec bezanan (har hit spell 5% hp player damage mide) in spell bad az koshtan 4 boss disable mishe

Violent Winds(191797):
bad az koshtan 2 boss har 90 sanie be modat 10sanie bayad biofte ro hame player ha

Lightning Strike(192794):
bad az koshtan 3 boss har 12 sanie miofte 2 yardi player ha bad az 3 sanie damage mizane

**Comment by AlirezaAbsolution** [comment]
> king deepbeard
> ground slam no ignore armor
> 
> wrath of azshara
> lighting strike ro nmizane
> arcane bomb mesle aura mimone

Arcane bomb:
192706 -> aura ro player k bayad dispell she
192708 -> stun ke bad az 12 sanie age player dispell nashe rosh miofte
192711 -> visual spell bomb ke donbal player miofte
?????? -> visual zir paye player ke alan ro yek infernal miofte

**Comment by newonee** [comment]
fixed
